name: CD

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2024-01-17
          targets: wasm32-unknown-unknown
          components: clippy, rustfmt

      - uses: jetli/trunk-action@v0.1.0
      - uses: jetli/wasm-bindgen-action@v0.1.0
      
      - uses: actions/checkout@v4

      - run: trunk build --release
      - run: find dist -name '*.wasm' -exec ./deps/wasm-opt -Oz -o {} {} \;
      - run: cp dist/index.html dist/404.html

      - uses: actions/upload-pages-artifact@v2
        with:
          path: dist
      - uses: actions/deploy-pages@v2
