name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2023-07-10
        override: true
        components: rustfmt,clippy

    steps:
    - uses: actions/checkout@v3
    - name: Run format
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy --all -- -D warnings
    - name: Run tests
      run: cargo test --verbose
